### ISSUE TITLE
cannot import name JsonResponse

### ISSUE THREAD

**Issue by nicchub** [juanifioren/django-openid-provider#2]
I get an import error installing DOP on Django 1.6, it's because JsonResponse is available only from >=  django 1.7

**Comment by juanifioren** [comment]
Yup sorry, for this moment I'll just add in the README that is for Django 1.7.
Maybe adding 1.6 support in a future.

Thanks.

**Comment by juanifioren** [comment]
For Django 1.6 support see #3

**Comment by sadaf2605** [comment]
on `django-admin --version`
1.9.2

```
from django.http import JsonRespons
ImportError: cannot import name JsonRespons
```

**Comment by juanifioren** [comment]
@sadaf2605 what django version are you using? The package is only supporting versions **>1.7**

**Comment by deepak1725** [comment]
Django Version: 1.9.7
from django.http import JsonResponse
Import Error

**Comment by ZubairKhan001** [comment]
from django.http import JsonResponse
django 4.2.15
solved
