### ISSUE TITLE
using pyoidc

### ISSUE THREAD

**Issue by cancan101** [juanifioren/django-openid-provider#7]
Any reason not to leverage [pyoidc](https://github.com/rohe/pyoidc)?

**Comment by juanifioren** [comment]
Hi @cancan101 ,
I was looking some lib for implementing a provider in Django. **pyoidc** was really complicated to understand, I couldn't even make it work. Discovery, provider, wsgi and cli are mixed.

There are some questions on Stackoverflow about this:
http://stackoverflow.com/questions/28193250/openid-connect-provider-in-python
http://stackoverflow.com/questions/21376619/openid-connect-provider-python-3
They also seem to have problems with rohe's library.

Greetings.

**Comment by cancan101** [comment]
Understood. What are your thoughts on:
* https://github.com/GehirnInc/python-oidc
* https://github.com/SteelPangolin/flask-oidc
* https://github.com/intelie/django-oidc-auth (client library)
