### ISSUE TITLE
LOGIN_URL in settings.py in README

### ISSUE THREAD

**Issue by cancan101** [juanifioren/django-openid-provider#9]
The `README` shows the following in `settings.py`:
```
# Used to log the user in.
# See: https://docs.djangoproject.com/en/1.7/ref/settings/#login-url
LOGIN_URL = '/accounts/login/'
```
but it is not clear why `LOGIN_URL` is required or what it should be set to ('/accounts/login/' ?).

**Comment by juanifioren** [comment]
It's used by the **authorization endpoint** to authenticate end-user into the provider.
Following: http://openid.net/specs/openid-connect-core-1_0.html#Authenticates
In our case, is just a view that log the user into Django.

The default value is the same that use the framework.

**Comment by cancan101** [comment]
That is the redirect that occurs here: https://github.com/juanifioren/django-openid-provider/blob/77d1bf86e825e02506bcfa1c3ca7dca77900b04a/openid_provider/views.py#L47 ?

If so, shouldn't it redirect back to the authorization view once the user is logged in?

**Comment by juanifioren** [comment]
It does!
If user is not logged, it redirect to login view. Url will be something like this:
```
http://your.provider/accounts/login/?next=/openid/authorize/%3Fclient_id%3D123%26response_type%3Dcode%26scope%3Dopenid%2520email ...
```
After login succeed it redirect back to the authorization view, and the flow continue ...

**Comment by cancan101** [comment]
Ah I see.

That being said you can clean up this:
```
                return redirect_to_login(
                    path, settings.get('LOGIN_URL'), REDIRECT_FIELD_NAME)
```
to just be:
```
                return redirect_to_login(path)
```
See the implementation of [`redirect_to_login`](https://github.com/django/django/blob/12562747508032725d4366c08b19dd26a8ce8a0c/django/contrib/auth/views.py#L122).

**Comment by juanifioren** [comment]
Thanks for that @cancan101. 7c49df79889ad18c497f4c0c08f8e6b2dd980b7d

**Comment by cancan101** [comment]
@juanifioren not sure if you saw this, but you might be able to clean up even further using: `login_required`.

**Comment by juanifioren** [comment]
@cancan101, using `login_required` decorator, user login will be checked before the **request validation**. Following OIDC draft, request validation happens first.

**Comment by cancan101** [comment]
that does not have to be the case. You could create an inner function and just wrap that:
```python
    def get(self, request, *args, **kwargs):

        authorize = AuthorizeEndpoint(request)

        try:
            authorize.validate_params()

             @login_required
             def impl(request, *args, **kwargs):
                # Generate hidden inputs for the form.
                context = {
                    'params': authorize.params,
                }
                hidden_inputs = render_to_string(
                    'openid_provider/hidden_inputs.html', context)

                # Remove openid from scope list since we don't need to print it.
                authorize.params.scope.remove('openid')

                context = {
                    'client': authorize.client,
                    'hidden_inputs': hidden_inputs,
                    'params': authorize.params,
                }

                return render(request, 'openid_provider/authorize.html', context)

           impl(request, args, **kwrgs)

        except (ClientIdError, RedirectUriError) as error:
            context = {
                'error': error.error,
                'description': error.description,
            }

            return render(request, 'openid_provider/error.html', context)

        except (AuthorizeError) as error:
            uri = error.create_uri(
                authorize.params.redirect_uri,
                authorize.params.state)
```
